name: ${{values.component_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag for dockerhub version
        shell: bash
        run: |
          echo "IMAGE_VERSION=$(date +'%y%m%d-%H%M')" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ vars.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnyunez/${{values.component_name}}:${{ '${{ env.IMAGE_VERSION }}' }}
    outputs:
      image_version: ${{ '${{ env.IMAGE_VERSION }}' }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Install pip and yq & Update charts/values/image.tag tag with new dockerhub image
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y python3-venv python3-pip
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip install yq
          echo ${{ '${{ needs.ci.outputs.image_version }}' }}
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.image_version }}' }}"' ./charts/values-${{values.environment}}.yaml
      -
        name: Commit changes to charts/values/image.tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "github-actions.cd: update image tag to ${{ '${{ needs.ci.outputs.image_version }}' }}"
          branch: master
          file_pattern: "charts/values-${{values.environment}}.yaml"
      -
        name: Install Argocd + Argocd login + repo add +  app create + app sync
        shell: bash
        run: |
          sudo curl -sSLk -o /usr/local/bin/argocd https://argocd-server.argocd/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd 

          repo="https://github.com/YuneZoft/${{values.component_name}}.git"
          argocd login argocd-server.argocd \
            --insecure \
            --username ${{ '${{ vars.ARGOCD_USERNAME }}' }} \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

          argocd repo list | grep -q $repo \
            || argocd repo add $repo \
                --project default \
                --name ${{values.component_name}}

          argocd app get ${{values.component_name}} \
          || argocd app create ${{values.component_name}} \
            --repo $repo \
            --path charts \
            --revision master \
            --dest-namespace ${{values.component_name}}-${{values.environment}} \
            --values values-${{values.environment}}.yaml \
            --dest-server https://kubernetes.default.svc \
            --sync-policy manual \
            --sync-option CreateNamespace=true

          argocd app sync ${{values.component_name}}

          argocd app wait ${{values.component_name}} --health --timeout 300


